apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: T-Shirt-Inventory-SOAP-Service
  description: The T-Shirt Inventory Service
  tags:
    - store
    - rest
  links:
    - url: https://github.com/mpandav-tibco/dev-hub-templates/blob/mastart/templates/apis/
      title: GitHub Repo
      icon: github
    - url: https://github.com/mpandav-tibco/dev-hub-templates/blob/mastart/templates/apis/Soap-Example.wsdl
      title: WSDL Service
      icon: code
spec:
  type: WSDL
  lifecycle: experimental
  owner: team-c
  definition:
    $text: ./Soap-Example.wsdl
