# domain: ecommerce
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: e-commerce
  description: The e-commerce domain
spec:
  owner: group:default/ecommerce-team
---
# storefront.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: storefront
  description: The user-facing storefront website
spec:
  type: service
  lifecycle: production
  owner: ecommerce-team
  consumesApis:
    - catalog-api
    - cart-api
    - checkout-api
    - shipping-api
  dependsOn:
    - user-service
    - inventory-service
    - order-service
    - shipping-service
    - payment-gateway
    - catalog-database
---
# catalog-api.yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: catalog-api
  description: Provides product catalog information
spec:
  type: openapi
  lifecycle: production
  owner: catalog-team
  dependsOn:
    - catalog-database
    - inventory-service
  definition:
    $text: ../apis/catalog/catalog-api.yaml
---
# cart-api.yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: cart-api
  description: Manages shopping carts and user sessions
spec:
  type: openapi
  lifecycle: production
  owner: cart-team
  dependsOn:
    - cart-database
    - user-service
  definition:
    $text: ../apis/cart/cart-api.yaml
---
# checkout-api.yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: checkout-api
  description: Handles order processing and payment integration
spec:
  type: opemapi
  lifecycle: production
  owner: checkout-team
  dependsOn:
    - order-service
    - payment-gateway
  definition:
    $text: ../apis/checkout/checkout-api.yaml
---
# user-service.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: user-service
  description: Manages user accounts and authentication
spec:
  type: service
  lifecycle: production
  owner: user-team
  dependsOn:
    - user-database
---
# inventory-service.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: inventory-service
  description: Tracks product inventory levels
spec:
  type: service
  lifecycle: production
  owner: inventory-team
  dependsOn:
    - inventory-database
---
# order-service.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: order-service
  description: Processes and fulfills orders
spec:
  type: service
  lifecycle: production
  owner: order-team
  dependsOn:
    - order-database
    - inventory-service
    - shipping-service
---
# shipping-service.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shipping-service
  description: Integrates with shipping providers
spec:
  type: service
  lifecycle: production
  owner: shipping-team
  dependsOn:
    - shipping-api
---
# shipping-api.yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: shipping-api
  description: Provides shipping rates and tracking information
spec:
  type: openapi
  lifecycle: production
  owner: shipping-team
  definition:
    $text: ../apis/shipment-tracking/shipping-api.yaml
---
# payment-gateway.yaml
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: payment-gateway
  description: External payment gateway service
spec:
  type: resource
  lifecycle: production
  owner: payments-team
---
# catalog-database.yaml
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: catalog-database
  description: Database for product catalog data
spec:
  type: resource
  lifecycle: production
  owner: database-team
---
# cart-database.yaml
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cart-database
  description: Database for shopping cart data
spec:
  type: resource
  lifecycle: production
  owner: database-team
---
# user-database.yaml
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: user-database
  description: Database for user account data
spec:
  type: resource
  lifecycle: production
  owner: database-team
---
# order-database.yaml
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: order-database
  description: Database for order information
spec:
  type: resource
  lifecycle: production
  owner: database-team
---
# inventory-database.yaml
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: inventory-database
  description: Database for inventory data
spec:
  type: resource
  lifecycle: production
  owner: database-team
---

