apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ecommerce-platform
spec:
  owner: ecommerce-team
  domain: e-commerce
  components:
    - name: storefront
      type: service
      lifecycle: production
      description: The user-facing storefront website
      consumesApi:
        - catalog-api
        - cart-api
        - checkout-api
        - shipping-api
      dependsOn:
        - user-service
        - inventory-service
        - order-service
        - shipping-service
        - payment-gateway
        - catalog-database
    - name: catalog-api
      type: api
      lifecycle: production
      description: Provides product catalog information
      dependsOn:
        - catalog-database
        - inventory-service
    - name: cart-api
      type: api
      lifecycle: production
      description: Manages shopping carts and user sessions
      dependsOn:
        - cart-database
        - user-service
    - name: checkout-api
      type: api
      lifecycle: production
      description: Handles order processing and payment integration
      dependsOn:
        - order-service
        - payment-gateway
    - name: user-service
      type: service
      lifecycle: production
      description: Manages user accounts and authentication
      dependsOn:
        - user-database
    - name: inventory-service
      type: service
      lifecycle: production
      description: Tracks product inventory levels
      dependsOn:
        - inventory-database
    - name: order-service
      type: service
      lifecycle: production
      description: Processes and fulfills orders
      dependsOn:
        - order-database
        - inventory-service
        - shipping-service
    - name: shipping-service
      type: service
      lifecycle: production
      description: Integrates with shipping providers
      dependsOn:
        - shipping-api
    - name: shipping-api
      type: api
      lifecycle: production
      description: Provides shipping rates and tracking information
    - name: payment-gateway
      type: resource
      lifecycle: production
      description: External payment gateway service
    - name: catalog-database
      type: resource
      lifecycle: production
      description: Database for product catalog data
    - name: cart-database
      type: resource
      lifecycle: production
      description: Database for shopping cart data
    - name: user-database
      type: resource
      lifecycle: production
      description: Database for user account data
    - name: order-database
      type: resource
      lifecycle: production
      description: Database for order information
    - name: inventory-database
      type: resource
      lifecycle: production
      description: Database for inventory data
