site_name: E-Commerce Platform Documentation
site_description: Technical documentation for the e-commerce platform
site_author: Your Name or Team Name
nav:
  - Overview: index.md
  - Architecture: index.md#architecture
  - Components:
      - Storefront: #storefront
      - Catalog Service: #catalog-service
      - Cart Service: #cart-service
      - Order Service: #order-service
      - Payment Service: #payment-service
      - User Service: #user-service
      - Inventory Service: #inventory-service
      - Shipping Service: #shipping-service
  - Data Management: #data-management
  - Deployment: #deployment
  - Monitoring and Logging: #monitoring-and-logging
  - Security: #security
  - Future Enhancements: #future-enhancements
plugins:
  - search
  - techdocs-core
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.code.annotate
    - search.highlight
    - search.suggest
    - search.share
