# system: ecommerce
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: tibco-global-platform
  description: This system comprises a collection of interconnected services and APIs, including a storefront web application, catalog management, shopping cart functionality, order processing, and payment integration. It leverages a microservices architecture to provide scalability and flexibility
  tags:
    - integration
    - microservices
    - tibco
    - templates
spec:
  owner: tibco-team
  domain: global-templates
  environments:
    - name: production
      baseUrl: https://ecommerce.example.com
    - name: staging
      baseUrl: https://staging.ecommerce.example.com
    - name: development
      baseUrl: https://dev.ecommerce.example.com
---
# domain: ecommerce
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: global-templates
  description: The global-templates domain
  tags:
    - integration
    - microservices
    - tibco
    - templates
spec:
  owner: group:default/tibco-team
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: tibco-team
  description: The team responsible for template creation and maintenance
spec:
  type: team
  profile:
    displayName: tibco-team
    email: tibco-team@example.com
  parent: []
    children: []
  members: [jdoe]
